/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2019-01-21 12:23:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class damier_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<title>Damier</title>\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styleDamier.css\">\n");
      out.write("\t</head>\n");
      out.write("\t\n");
      out.write("\t<body>\n");
      out.write("\t\t");

		 String[] nomsVilles =  { 
		 						  "Marseille", "Lyon", "Grenoble", "Nantes", "Strasbourg",
		 						  "Montpellier", "Bordeaux","Paris", "Lille", "Rennes",
		 						  "Angers", "Reims", "Le Havre", "Toulouse", "Saint-Etienne", "Toulon",
		 						  "Dijon", "Brest", "Nimes", "Nice"
		 						};

		 Arrays.sort(nomsVilles);

		
      out.write("\n");
      out.write("\t\t<h1>Damier de 10 lignes par 10 colonnes</h1>\n");
      out.write("\n");
      out.write("\t\t<table style=\"border: 1px solid red\">\n");
      out.write("\t\t\t");

				String type = new String();

				for(int cptLig=0; cptLig<10; cptLig++){
					out.println("<tr style=\"border: 1px solid black\">");

					if(cptLig % 2 == 0) type = "blanc" ;
					else 				type = "noir";

					for (int cptCol=0; cptCol<10; cptCol++){
						

						out.println("<td style=\"border: 1px solid red\" " +"class= " +type+ ">" + "</td>");

						if(type.equals("blanc")) type = "noir" ;
						else 					 type = "blanc";
					}

					out.println("</tr>");
				}				
			
      out.write("\n");
      out.write("\t\t</table>\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
