/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2019-01-21 10:38:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import annexe.Personne;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {



		public int somme(int a, int b){
			return a+b;
		}

		int x = 22;
		int y = 10;

		
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<title>Personne</title>\n");
      out.write("\t</head>\n");
      out.write("\t\n");
      out.write("\t<body>\n");
      out.write("\t\t");
      out.write("\n");
      out.write("\n");
      out.write("\t\t");
 
		System.out.println("appli 1 lancée");
		Date d = new Date();
		out.println(" Nous sommes le "+ d);
		
      out.write("\n");
      out.write("\n");
      out.write("\t\t");

		out.println("<br />");
		out.println(x + " + " + y + " = " +somme(x,y));

		x++;
		y++;

		out.println("<br />");

		Personne p1 = new Personne("Paccard", "Patrick", 20);
		Personne p2 = new Personne("Deville", "Francis", 45);
		Personne p3 = new Personne("Rialto", "Clémence", 62);

		Personne[] tabPers = new Personne[3];
		tabPers[0] = p1;
		tabPers[1] = p2;
		tabPers[2] = p3;

		
      out.write("\n");
      out.write("\n");
      out.write("\t\t");
      out.print( p1 );
      out.write("\n");
      out.write("\t\t<br />\n");
      out.write("\t\t<br />\n");
      out.write("\n");
      out.write("\t\t<table style=\"border: 1px solid red\">\n");
      out.write("\t\t\t");

				for(Personne pers: tabPers){
					out.println("<tr style=\"border: 1px solid red\">");

					out.println("<td style=\"border: 1px solid red\">" +pers.getNom   ()+ "</td>");
					out.println("<td style=\"border: 1px solid red\">" +pers.getPrenom()+ "</td>");
					out.println("<td style=\"border: 1px solid red\">" +pers.getAge   ()+ "</td>");

					out.println("</tr>");
				}
			
      out.write("\n");
      out.write("\t\t</table>\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
