/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package philosophes.ihm;

import java.awt.GridLayout;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JButton;
import philosophes.Controleur;

/**
 *
 * @author labbeh
 */
public class IHMGui extends javax.swing.JFrame {
    /**
     * Accès à l'instance du controleur
     */
    private Controleur ctrl;
    
    /**
     * Ensembles des boutons associés aux philosophes
     */
    private Map<String,JButton> btnsPhilos;
    

    /**
     * Creates new form IHMGui
     */
    public IHMGui(Controleur ctrl) {
        this.ctrl = ctrl;
        this.btnsPhilos = new HashMap<>(ctrl.getNbPhilosophes());
        //this.btnsAss = new JButton[]
        
        initComponents();
    }
    
    public void setNbAssiettes(int nb){
        nbAss.setText(Integer.toString(nb));
    }
    
    /**
     * Permet de changer l'état d'un philosophe
     */
    public void setEtat(String nom, String etat){
        StringBuilder sb = new StringBuilder("<html>");
        sb.append(nom).append("<br />");
        sb.append(etat);
        
        btnsPhilos.get(nom).setText(sb.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPhilo = new javax.swing.JPanel();
        panelAss = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nbAss = new javax.swing.JLabel();
        lancer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelPhiloLayout = new javax.swing.GroupLayout(panelPhilo);
        panelPhilo.setLayout(panelPhiloLayout);
        panelPhiloLayout.setHorizontalGroup(
            panelPhiloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );
        panelPhiloLayout.setVerticalGroup(
            panelPhiloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelPhilo.setLayout(new GridLayout(ctrl.getNbPhilosophes()/2, ctrl.getNbPhilosophes()/2));

        jLabel1.setText("Nombre d'assiettes restantes:");

        javax.swing.GroupLayout panelAssLayout = new javax.swing.GroupLayout(panelAss);
        panelAss.setLayout(panelAssLayout);
        panelAssLayout.setHorizontalGroup(
            panelAssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAssLayout.createSequentialGroup()
                .addGroup(panelAssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAssLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(panelAssLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(nbAss)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAssLayout.setVerticalGroup(
            panelAssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAssLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(nbAss)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        lancer.setText("Lancer");
        lancer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lancerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPhilo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lancer)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPhilo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(panelAss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(lancer)
                .addContainerGap())
        );

        for(int i=0; i<ctrl.getNbPhilosophes(); i++){
            JButton btnPhilo = new JButton(ctrl.getPhilosophe(i).getNom());
            btnPhilo.setEnabled(false);
            panelPhilo.add(btnPhilo);
            btnsPhilos.put(ctrl.getPhilosophe(i).getNom(), btnPhilo);

        }

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lancerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lancerActionPerformed
        ctrl.animerPhilosophes();
        lancer.setEnabled(false);
    }//GEN-LAST:event_lancerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IHMGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IHMGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IHMGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IHMGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IHMGui(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton lancer;
    private javax.swing.JLabel nbAss;
    private javax.swing.JPanel panelAss;
    private javax.swing.JPanel panelPhilo;
    // End of variables declaration//GEN-END:variables
}
